services:
  db:
    image: postgres:17
    container_name: application_chat_db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=application_chat
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ftp_server:
    image: fauria/vsftpd
    container_name: ftp_server
    restart: unless-stopped
    environment:
      - FTP_USER=user
      - FTP_PASS=password
      - PASV_ADDRESS=localhost
      - PASV_MIN_PORT=30000
      - PASV_MAX_PORT=30009
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp_data:/home/ftpuser