server:
  port: 8080

encryption:
  key: 18'XY5W^:@LhW^V8NiEUftJ@+jd|LWOS
  algorithm: AES
  transformation: AES/CBC/PKCS5Padding

spring:
  application:
    name: application_chat

  datasource:
    url: jdbc:postgresql://localhost:6432/application_chat
    username: user
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

ftp:
  host: localhost
  port: 21
  username: user
  password: password
  remote-directory: /icons